### ISSUE TITLE
La pagina di autenticazione di Aruba da errore

### ISSUE THREAD

**Issue by cloudify** [italia/spid-sp-playbook#17]
Usando come entityId dell'IdP quello di Aruba (es. `https://myhost/saml/Login?target=/app&entityID=https://loginspid.aruba.it` si ottiene una pagina di errore.

<img width="372" alt="spid" src="https://cloud.githubusercontent.com/assets/48206/26256690/10a055e8-3cbe-11e7-804a-9a2b11cbf74f.png">

**Comment by umbros** [comment]
Blocco su firma sha256 fixed!

**Comment by cloudify** [comment]
fixed by 46d6dee2aae7e66fb1227d3cb97541372462980a
