### ISSUE TITLE
installazione playbook

### ISSUE THREAD

**Issue by eros2187** [italia/spid-sp-playbook#20]
buongiorno ce qualche guida che spiega come poter provare questo repository?
sto cercando un esempio di spid da poter implementare con  una mia piattaforma cms.
 purtroppo non conosco questo metodo  playbook quindi sarebbe utile spiegare come poterlo provare grazie!

**Comment by donatomaio** [comment]
esiste una guida?

**Comment by alranel** [comment]
Bisogna installare Ansible e poi eseguire il comando indicato nel README di questo repository. Funziona solo su sistemi che usano "apt" come gestore di pacchetti. Per tutti gli altri è possibile installare Shibboleth manualmente e copiare le configurazioni che si trovano in questo repository.
