### ISSUE TITLE
Documentare installazione manuale Shibboleth

### ISSUE THREAD

**Issue by alranel** [italia/spid-sp-playbook#23]
Sarebbe utile scrivere una piccola guida su come installare e configurare manualmente Shibboleth. Questo playbook funziona solo su alcuni sistemi operativi e in generale un playbook Ansible o anche un docker non si adattano all'integrazione con sistemi esistenti.

La guida dovrebbe anche spiegare come integrare Shibboleth a livello applicativo attraverso esempi di chiamate, visto che la documentazione originale di Shibboleth è ampia, un po' accademica, e non è chiaro cosa si applica a SPID e cosa no.

**Comment by peppelinux** [comment]
fare riferimento a https://github.com/italia/spid-sp-shibboleth
e a https://github.com/italia/spid-ansible-shibboleth-example/issues/34
