### ISSUE TITLE
Possibile errore nel playbook

### ISSUE THREAD

**Issue by brunato** [italia/spid-sp-playbook#24]
Ho provato a usare il playbook (con ansible 2.4 per la configurazione, le VM sono Ubuntu server 16.04 e 17.04), ma mi pare ci sia un errore nella configurazione del container shibboleth-nginx che viene creato. Il file `/etc/shibboleth/spidMetadata.xml ` non è più un file XML come nel repo ma una directory vuota:
 
```
#` docker ps --all
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                      PORTS               NAMES
93f4dbe15c29        bradjonesllc/docker-nginx-letsencrypt   "/bootstrap.sh"          18 seconds ago      Exited (1) 13 seconds ago                       nginx-letsencrypt
a6da989f79e5        virtualstaticvoid/shibboleth-nginx      "/usr/local/bin/ep -v"   20 seconds ago      Up 18 seconds               80/tcp, 9090/tcp    shibboleth-nginx
e517bbe53ac0        readytalk/nodejs-hello                  "/nodejs/bin/npm star"   24 seconds ago      Up 23 seconds               8080/tcp            app-backend
# docker exec -ti a6da989f79e5 bash
root@a6da989f79e5:/# ls -la /etc/shibboleth/spidMetadata.xml/
total 8
drwxr-xr-x 2 root root 4096 Oct 23 07:29 .
drwxr-xr-x 5 root root 4096 Oct 24 12:01 ..
```

**Comment by brunato** [comment]
Aggiungo da prove ulteriori che ho fatto con questo playbook che la generazione dei metadati non funziona. Non so se questo è dovuto all'erorre nel template file spidMetadata.xml segnalato sopra. Funzionano invece correttamente la generazione delle richieste di autenticazione verso gli IdP SPID registrati.

**Comment by peppelinux** [comment]
Ciao @brunato 
fare riferimento a https://github.com/italia/spid-sp-shibboleth
e a https://github.com/italia/spid-ansible-shibboleth-example/issues/34
