### ISSUE TITLE
Playbook per Shibboleth

### ISSUE THREAD

**Issue by brunato** [italia/spid-sp-playbook#25]
Il playbook mi ha funzionato correttamente solo con macchina aperta per far funzionare il certbot di Let's Encrypt. E' nota questa limitazione? 

Nel caso non sarebbe meglio quindi definire come opzionale l'uso di Let's Encrypt nel playbook (installando un certificato autosigned in questi casi) oppure definire dei playbook alternativi che installano solo una parte (che ne so, solo Shibboleth con configurazione per SPID)?
 
Grazie

**Comment by cloudify** [comment]
ciao @brunato,
grazie per il feedback, si confermo che è così _by design_, l'opzione per installare un certificato autogenerato sarebbe molto utile, ti fa di proporre una pull request?

**Comment by brunato** [comment]
Benissimo, lavorerò per fare una PR per uno o più playbook alternativi.

**Comment by peppelinux** [comment]
fare riferimento a https://github.com/italia/spid-sp-shibboleth
e a https://github.com/italia/spid-ansible-shibboleth-example/issues/34
