### ISSUE TITLE
Spostare direttiva signingAlg (shibboleth2.xml)

### ISSUE THREAD

**Issue by francescm** [italia/spid-sp-playbook#29]
Gli schemi xml per shibboleth2.xml si aspettano che la direttiva signingAlg sia un attributo dell'elemento ApplicationDefaults (non SessionInitiator).
cfr: PR #28

**Comment by peppelinux** [comment]
fare riferimento a https://github.com/italia/spid-sp-shibboleth
e a https://github.com/italia/spid-ansible-shibboleth-example/issues/34
