### ISSUE TITLE
Pagina login di esempio

### ISSUE THREAD

**Issue by cloudify** [italia/spid-sp-playbook#3]
Va implementata una pagina di login di esempio con il bottone di login di SPID.

**Comment by alranel** [comment]
Dovrebbe essere sufficiente usare il [bottone SPID](https://github.com/italia/spid-sp-access-button) in modalità POST, ovvero inserendolo in un `<form action="/Shibboleth.sso/Login">` (con i vari campi `hidden` necessari) e dando il nome `entityID` al campo inviato dai `<button>` degli IdP.

Un esempio simile si può vedere [qui](https://wayf.cnr.it/index.html?entityID=https%3A%2F%2Fdl.cnr.it%2Fshibboleth&return=https%3A%2F%2Fdl.cnr.it%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A351b5009c94a96ec4ea595e79039ec669e9e0448b1e91a99e4b936d3622e459c). Si tratta di una pagina generata dall'[Embedded Discovery Service](https://wiki.shibboleth.net/confluence/display/EDS10/Embedded+Discovery+Service) di Shibboleth, che farebbe quasi al caso nostro se non fosse che non rispetta le linee guida di UI per SPID.

Questa integrazione diventerà ancora più pulita quando sarà completato lo [Smart Button](https://github.com/italia/spid-smart-button) che sarà offerto in modalità hosted, per cui l'unico markup necessario nella pagina di login dell'applicazione sarà `<form>` e poco altro.

**Comment by peppelinux** [comment]
fare riferimento a https://github.com/italia/spid-sp-shibboleth
e a https://github.com/italia/spid-ansible-shibboleth-example/issues/34
