### ISSUE TITLE
misconfigured ?

### ISSUE THREAD

**Issue by simevo** [italia/spid-sp-playbook#32]
https://spid-test.spc-app1.teamdigitale.it/app risponde con 302 redirect su:
```
https://posteid.poste.it/jod-fs/ssoserviceredirect?SAMLRequest=lV...
&RelayState=ss...
&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1
&Signature=V8...
```
che risponde con:
```
messaggio di avviso
Errore: Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio
```

**Comment by cloudify** [comment]
ciao @simevo temo che questo playbook non sia piu' mantenuto con le ultime configurazioni - cc @umbros @alexrj @ruphy

**Comment by peppelinux** [comment]
fare riferimento a https://github.com/italia/spid-sp-shibboleth
